version: "3"

services:
  node_1:
    build: .
    container_name: node_1
    volumes:
      - ./:/app
    ports:
      - "80:5000"
  node_2:
    build: .
    container_name: node_2
    volumes:
      - ./:/app
    ports:
      - "81:5000"
  node_3:
    build: .
    container_name: node_3
    volumes:
      - ./:/app
    ports:
      - "82:5000"

